from enum import Enum

class Area(Enum):
    CRATERIA = 0
    BRINSTAR = 1
    NORFAIR = 2
    WRECKED_SHIP = 3
    MARIDIA = 4
    TOURIAN = 5

class SubArea(Enum):
    WEST_CRATERIA = 1
    SOUTH_CRATERIA = 2
    CENTRAL_CRATERIA = 3
    EAST_CRATERIA = 4
    BLUE_BRINSTAR = 5
    GREEN_BRINSTAR = 6
    PINK_BRINSTAR = 7
    RED_BRINSTAR = 8
    WAREHOUSE_BRINSTAR = 9
    UPPER_NORFAIR = 10
    LOWER_NORFAIR = 11
    OUTER_MARIDIA = 12
    GREEN_MARIDIA = 13
    PINK_MARIDIA = 14
    YELLOW_MARIDIA = 15
    WRECKED_SHIP = 16
    UPPER_TOURIAN = 17
    LOWER_TOURIAN = 18
    ESCAPE_TOURIAN = 19
