from enum import Enum

class Area(Enum):
    CRATERIA = 0
    BRINSTAR = 1
    NORFAIR = 2
    WRECKED_SHIP = 3
    MARIDIA = 4
    TOURIAN = 5

class SubArea(Enum):
    CRATERIA_AND_BLUE_BRINSTAR = 1
    GREEN_AND_PINK_BRINSTAR = 2
    RED_BRINSTAR_AND_WAREHOUSE = 3
    LOWER_NORFAIR = 4
    UPPER_NORFAIR = 5
    OUTER_MARIDIA = 6
    INNER_MARIDIA = 7
    WRECKED_SHIP = 8
    TOURIAN = 9
