# Rooms (and screen positions within them) which are allowed to intersect the Toilet

toilet_rooms = [
    {"name": "Amphitheatre", "x": [0, 1, 2, 3]},
    {"name": "Aqueduct", "x": [2, 4, 5]},
    {"name": "Below Spazer", "x": [1]},
    {"name": "Beta Power Bomb Room", "x": [0]},
    {"name": "Bowling Alley", "x": [2, 3, 4]},
    {"name": "Bubble Mountain", "x": [1]},
    {"name": "Bat Cave", "x": [0]},
    {"name": "Cathedral Entrance", "x": [1, 2]},
    {"name": "Cathedral", "x": [0, 1, 2]},
    {"name": "Construction Zone", "x": [0]},
    {"name": "Crab Hole", "x": [0]},
    {"name": "Crocomire Escape", "x": [1]},
    {"name": "Crumble Shaft", "x": [0]},
    {"name": "Double Chamber", "x": [0, 1, 2, 3]},
    {"name": "The Moat", "x": [0, 1]},
    {"name": "The Precious Room", "x": [0]},
    {"name": "Early Supers Room", "x": [0, 1, 2]},
    {"name": "East Ocean", "x": [0, 1, 2, 3, 4, 5, 6]},
    {"name": "Electric Death Room", "x": [0]},
    {"name": "Etecoon Energy Tank Room", "x": [0]},
    {"name": "Fast Pillars Setup Room", "x": [0]},
    {"name": "Fish Tank", "x": [1]},
    {"name": "Grapple Beam Room", "x": [0]},
    {"name": "Grapple Tutorial Room 2", "x": [0]},
    {"name": "Ice Beam Snake Room", "x": [0]},
    {"name": "Kassiuz Room", "x": [0]},
    {"name": "Kraid Eye Door Room", "x": [0]},
    {"name": "Kronic Boost Room", "x": [1]},
    {"name": "Landing Site", "x": [3, 5]},
    {"name": "Lava Dive Room", "x": [1]},
    {"name": "Lower Norfair Spring Ball Maze Room", "x": [1]},
    {"name": "Mama Turtle Room", "x": [1, 2]},
    {"name": "Metroid Room 2", "x": [0]},
    {"name": "Mickey Mouse Room", "x": [3]},
    {"name": "Mt. Everest", "x": [3, 5]},
    {"name": "Northwest Maridia Bug Room", "x": [0]},
    {"name": "Pants Room", "x": [0, 1]},
    {"name": "Parlor And Alcatraz", "x": [3]},
    {"name": "Pink Brinstar Hopper Room", "x": [0, 1]},
    {"name": "Pink Brinstar Power Bomb Room", "x": [0]},
    {"name": "Plasma Room", "x": [0, 1]},
    {"name": "Plasma Spark Room", "x": [1, 2]},
    {"name": "Post Crocomire Farming Room", "x": [1]},
    {"name": "Post Crocomire Jump Room", "x": [0, 1, 2, 3]},
    {"name": "Pseudo Plasma Spark Room", "x": [1, 2]},
    {"name": "Red Kihunter Shaft", "x": [0]},
    {"name": "Rinka Shaft", "x": [0]},
    {"name": "Screw Attack Room", "x": [0]},
    {"name": "Seaweed Room", "x": [0]},
    {"name": "Single Chamber", "x": [0]},
    {"name": "The Worst Room In The Game", "x": [0]},
    {"name": "Three Musketeers' Room", "x": [1]},
    {"name": "Tourian Escape Room 3", "x": [0, 1, 2, 3, 4, 5]},
    {"name": "Tourian Escape Room 4", "x": [0, 1, 2]},
    {"name": "Volcano Room", "x": [2]},
    {"name": "Wasteland", "x": [1]},
    {"name": "Warehouse Entrance", "x": [1]},
    {"name": "Watering Hole", "x": [0]},
    {"name": "West Cactus Alley Room", "x": [0]},
    {"name": "West Ocean", "x": [0, 1, 2, 5]},
    {"name": "Wrecked Ship Energy Tank Room", "x": [1, 2]},
]
