"""Print a Logic updates HTML block comparing working-tree data with v{VERSION-1}.

Run from any directory. Empty sections and currently Uncategorized entries are
omitted; entries moved from Uncategorized or Ignored count as new.

With --update, replace only the marked list items in the current release in
releases.html. Missing markers leave the file unchanged. Remove both markers
to take manual control; put additional manual notes outside the markers.
When GITHUB_OUTPUT is set, --update writes status=updated, unchanged, or skipped.
"""

import argparse
import html
import json
import os
from pathlib import Path
import re
import subprocess
import sys


DIFFICULTIES = [
    "Implicit", "Basic", "Medium", "Hard", "Very Hard", "Expert", "Expert+",
    "Extreme", "Extreme+", "Insane", "Insane+", "Beyond", "Ignored",
]
BEGIN_MARKER = "<!-- BEGIN AUTOGENERATED LOGIC UPDATES - DO NOT MANUALLY EDIT -->"
END_MARKER = "<!-- END AUTOGENERATED LOGIC UPDATES -->"


def load_previous(repo, tag, path):
    result = subprocess.run(
        ["git", "show", f"{tag}:{path}"], cwd=repo,
        check=True, capture_output=True, text=True,
    )
    return json.loads(result.stdout)


def entry_key(entry, kind):
    if kind == "tech":
        return (entry["tech_id"],)
    return (entry["room_id"], entry["notable_id"])


def entry_link(entry, kind):
    ids = "/".join(str(value) for value in entry_key(entry, kind))
    name = entry["name"]
    if kind == "notable":
        name = f'{entry["room_name"]}: {name}'
    return f'<a href="/logic/{kind}/{ids}">{html.escape(name)}</a>'


def make_sections(current, previous, kind):
    previous_by_id = {entry_key(entry, kind): entry for entry in previous}
    new_entries = []
    moved_entries = []
    # Sort by current difficulty, preserving source order within each tier.
    difficulty_order = {name: index for index, name in enumerate(DIFFICULTIES)}
    current = sorted(
        current,
        key=lambda entry: difficulty_order.get(entry["difficulty"], len(DIFFICULTIES)),
    )
    for entry in current:
        difficulty = entry["difficulty"]
        if difficulty == "Uncategorized":
            continue
        previous_entry = previous_by_id.get(entry_key(entry, kind))
        link = entry_link(entry, kind)
        if (
            previous_entry is None
            or previous_entry["difficulty"] == "Uncategorized"
            or (previous_entry["difficulty"] == "Ignored" and difficulty != "Ignored")
        ):
            new_entries.append(f"{link} ({html.escape(difficulty)}).")
        elif previous_entry["difficulty"] != difficulty:
            old_difficulty = html.escape(previous_entry["difficulty"])
            moved_entries.append(
                f"{link} is moved from {old_difficulty} to {html.escape(difficulty)}."
            )
    return new_entries, moved_entries


def render_section(title, entries):
    if not entries:
        return []
    return [
        f"    <li>{title}:",
        "        <ul>",
        *(f"        <li>{entry}" for entry in entries),
        "        </ul>",
    ]


def generate_items(repo, version):
    tag = f"v{version - 1}"
    sections = {}
    for kind, filename in [("tech", "tech_data.json"), ("notable", "notable_data.json")]:
        path = f"rust/data/{filename}"
        current = json.loads((repo / path).read_text())
        previous = load_previous(repo, tag, path)
        sections[kind] = make_sections(current, previous, kind)

    lines = []
    for title, entries in [
        ("New tech", sections["tech"][0]),
        ("New notables", sections["notable"][0]),
        ("Tech moved to a different difficulty level", sections["tech"][1]),
        ("Notables moved to a different difficulty level", sections["notable"][1]),
    ]:
        lines.extend(render_section(title, entries))
    return lines


def find_generated_block(text, version):
    releases = list(re.finditer(r'<a\b[^>]*\bid=[\"\']release(\d+)[\"\'][^>]*>', text))
    matches = [i for i, release in enumerate(releases) if int(release[1]) == version]
    if len(matches) != 1:
        raise ValueError(f"Expected exactly one release{version} anchor in releases.html")
    index = matches[0]
    start = releases[index].end()
    end = releases[index + 1].start() if index + 1 < len(releases) else len(text)
    release_text = text[start:end]
    if BEGIN_MARKER not in release_text and END_MARKER not in release_text:
        return None
    if release_text.count(BEGIN_MARKER) != 1 or release_text.count(END_MARKER) != 1:
        raise ValueError(f"Incomplete or duplicate autogenerated markers in release{version}")
    begin = re.search(r"^[ \t]*" + re.escape(BEGIN_MARKER) + r"[ \t]*\n", release_text, re.M)
    finish = re.search(r"^[ \t]*" + re.escape(END_MARKER) + r"[ \t]*$", release_text, re.M)
    if begin is None or finish is None or begin.end() > finish.start():
        raise ValueError(f"Autogenerated markers must be on separate lines in order in release{version}")
    return start + begin.end(), start + finish.start()


def update_release_notes(repo, version):
    path = repo / "rust/maprando-web/templates/releases.html"
    text = path.read_text()
    bounds = find_generated_block(text, version)
    if bounds is None:
        print(f"Release notes skipped: release{version} has no autogenerated markers.", file=sys.stderr)
        return "skipped"
    lines = generate_items(repo, version)
    replacement = "\n".join(lines) + ("\n" if lines else "")
    start, end = bounds
    updated = text[:start] + replacement + text[end:]
    if updated == text:
        return "unchanged"
    path.write_text(updated)
    return "updated"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--update", action="store_true", help="Update the marked items in releases.html.")
    args = parser.parse_args()
    repo = Path(__file__).resolve().parents[2]
    version = int((repo / "rust/VERSION").read_text().strip())
    if args.update:
        status = update_release_notes(repo, version)
        print(f"Release notes: {status}.", file=sys.stderr)
        if os.environ.get("GITHUB_OUTPUT"):
            with open(os.environ["GITHUB_OUTPUT"], "a") as output:
                output.write(f"status={status}\n")
        return
    lines = generate_items(repo, version)
    if lines:
        print("\n".join(["<li>Logic updates:", "    <ul>", *lines, "    </ul>"]))


if __name__ == "__main__":
    try:
        main()
    except subprocess.CalledProcessError as exc:
        print(f"Unable to read previous release data: {exc.stderr.strip()}", file=sys.stderr)
        sys.exit(1)
    except (OSError, ValueError, KeyError) as exc:
        print(f"Unable to generate logic release notes: {exc}", file=sys.stderr)
        sys.exit(1)
