from enum import Enum

class Area(Enum):
    CRATERIA_AND_BLUE_BRINSTAR = 1
    BRINSTAR = 2
    NORFAIR = 3
    MARIDIA = 4
    WRECKED_SHIP = 5
    TOURIAN = 6

class SubArea(Enum):
    CRATERIA_AND_BLUE_BRINSTAR = 1
    GREEN_AND_PINK_BRINSTAR = 2
    RED_BRINSTAR_AND_WAREHOUSE = 3
    LOWER_NORFAIR = 4
    UPPER_NORFAIR = 5
    LOWER_MARIDIA = 6
    UPPER_MARIDIA = 7
    WRECKED_SHIP = 8
    TOURIAN = 9
