const offsets = {
	"Morph Ball Room: Left Item": [2, 2],
	"Morph Ball Room: Right Item": [4, 2],
	"Cathedral: Hidden Item": [2, 1],
	"The Precious Room: Top Right Hidden Item": [1, 0],
	"Mama Turtle Room: Hidden Right Item": [2, 1],
	"Mama Turtle Room: Top Item": [1, 0],
	"Brinstar Reserve Tank Room: Middle Visible Item": [0.75, 0],
	"Brinstar Reserve Tank Room: Right Hidden Item": [1.25, 0],
	"Brinstar Reserve Tank Room: Chozo Item": [0, 0],
	"Lower Norfair Fireflea Room: Firefleas Item": [2, 5],
	"Main Street: Morph Tunnel Item": [1, 2],
	"Main Street: Speed Blocked Item": [0, 3],
	"Gauntlet Energy Tank Room: Item": [5, 0],
	"Wrecked Ship Main Shaft: Item": [0, 5],
	"Pseudo Plasma Spark Room: Hidden Item": [2, 2],
	"Assembly Line: Item": [2, 0],
	"Warehouse Kihunter Room: Hidden Item": [2, 0],
	"Billy Mays Room: Pedestal Item": [0.25, 0],
	"Billy Mays Room: Hidden Item": [-0.25, 0],
	"Norfair Reserve Tank Room: Hidden Platform Item": [0.5, 0],
	"Green Hill Zone: Item (Through the Pipe)": [3, 1],
	"Crocomire's Room: Item": [7, 0],
	"Blue Brinstar Energy Tank Room: Hidden Ceiling Item": [1, 2],
	"Blue Brinstar Energy Tank Room: Right Item": [2, 2],
	"Three Musketeers' Room: Hidden Item": [0, 2],
	"Alpha Power Bomb Room: Chozo Item": [1, 0],
	"Alpha Power Bomb Room: Hidden Left Item": [0, 0],
	"Aqueduct: Top Right Right Item": [5, 0],
	"Aqueduct: Top Right Left Item": [4, 0],
	"Screw Attack Room: Item": [0, 2],
	"Bubble Mountain: Bottom Right Item": [1, 3],
	"Watering Hole: Left Item": [-0.25, 2],
	"Watering Hole: Right Item": [0.25, 2],
	"Speed Booster Room: Hidden Item": [11, 1],
	"West Sand Hole: Top Left - Right Item": [0.25, 0],
	"West Sand Hole: Top Left - Left Item": [-0.25, 0],
	"East Sand Hole: Top Left Item": [0, 0],
	"East Sand Hole: Right Item": [1, 1],
	"Post Crocomire Missile Room: Item": [3, 0],
	"Double Chamber: Item": [1, 0],
	"Beta Power Bomb Room: Item": [0, 1],
	"West Ocean: Bottom Left Underwater Item": [0, 5],
	"West Ocean: Left Morph Maze Item": [0, 2],
	"West Ocean: Top Hidden Item (Above Trippers)": [1, 0],
	"Early Supers Room: Lower Item": [1, 1],
	"Early Supers Room: Top Left Item": [0, 0],
	"Plasma Room: Item": [1, 2],
	"Green Pirates Shaft: Left Item": [-0.25, 1],
	"Green Pirates Shaft: Right Item": [0.25, 1],
	"Spring Ball Room: Item": [1, 1],
	"Pink Brinstar Power Bomb Room: Item": [0, 1],
	"Pit Room: Item": [0, 1],
	"Mickey Mouse Room: Item": [2, 1],
	"Grapple Beam Room: Item": [0, 2],
	"Golden Torizo's Room: Hidden Right Item": [1, 0],
	"Golden Torizo's Room: Top Left Item": [0, 0],
	"Wrecked Ship East Super Room: Item (Behind the Bomb Wall)": [3, 0],
	"Botwoon Energy Tank Room: Item": [3, 0],
	"Terminator Room: Item": [0, 2],
	"Post Crocomire Jump Room: Item": [4, 0],
	"Green Bubbles Missile Room: Item": [1, 0],
	"Lower Norfair Spring Ball Maze Room: Item": [2, 0],
	"Crateria Power Bomb Room: Item": [1, 0],
	"Green Brinstar Main Shaft: Right Etecoon Shaft - Item": [3, 7],
	"Crateria Super Room: Item": [3, 0],
	"Spore Spawn Super Room: Item": [1, 8],
	"Hi Jump Energy Tank Room: Top Right Item": [1, 0],
	"Hi Jump Energy Tank Room: Top Left Item": [0, 0],
	"Big Pink: Top Item (Above Hopper Pit)": [2, 3],
	"Big Pink: Middle Item": [2, 6],
	"Big Pink: Bottom Chozo Item": [2, 7],
	"Bowling Alley: Bottom Chozo Item": [3, 2],
	"Bowling Alley: Top Right Item": [5, 0],
};
let item_plm = {
	"ETank": 0,
	"Missile": 1,
	"Super": 2,
	"PowerBomb": 3,
	"Bombs": 4,
	"Charge": 5,
	"Ice": 6,
	"HiJump": 7,
	"SpeedBooster": 8,
	"Wave": 9,
	"Spazer": 10,
	"SpringBall": 11,
	"Varia": 12,
	"Gravity": 13,
	"XRayScope": 14,
	"Plasma": 15,
	"Grapple": 16,
	"SpaceJump": 17,
	"ScrewAttack": 18,
	"Morph": 19,
	"ReserveTank": 20,
	"WallJump": 21,
};
let item_rank = {
	"Varia": 1,
	"Gravity": 2,
	"Morph": 3,
	"SpaceJump": 4,
	"ScrewAttack": 5,
	"WallJump": 6,
	"Bombs": 7,
	"HiJump": 8,
	"SpeedBooster": 9,
	"SpringBall": 10,
	"Grapple": 11,
	"XRayScope": 12,
	"Charge": 13,
	"Ice": 14,
	"Wave": 15,
	"Spazer": 16,
	"Plasma": 17,
	"ETank": 18,
	"ReserveTank": 19,
	"Super": 20,
	"PowerBomb": 21,
	"Missile": 22,
};
let roomFlags = {
	"Bomb Torizo Room": ["f_DefeatedBombTorizo", "Defeat Bomb Torizo", 0,0,32],
	"Botwoon's Room": ["f_DefeatedBotwoon", "Defeat Botwoon",0,0,32],
	"Crocomire's Room": ["f_DefeatedCrocomire", "Defeat Crocomire",4,0,32],
	"Draygon's Room": ["f_DefeatedDraygon", "Defeat Draygon",0,0,48],
	"Golden Torizo's Room": ["f_DefeatedGoldenTorizo", "Defeat Golden Torizo",1,1,32],
	"Kraid Room": ["f_DefeatedKraid", "Defeat Kraid",0.5,0,48],
	"Mother Brain Room": ["f_DefeatedMotherBrain", "Defeat Mother Brain",0,-1,48],
	"Phantoon's Room": ["f_DefeatedPhantoon", "Defeat Phantoon",0,0,32],
	"Ridley's Room": ["f_DefeatedRidley", "Defeat Ridley",0,0,48],
	"Spore Spawn Room": ["f_DefeatedSporeSpawn", "Defeat Spore Spawn",0,2,32],
	"Metroid Room 1": ["f_KilledMetroidRoom1", "Clear Metroid Room 1",2.5,0,32],
	"Metroid Room 2": ["f_KilledMetroidRoom2", "Clear Metroid Room 2",0,1,32],
	"Metroid Room 3": ["f_KilledMetroidRoom3", "Clear Metroid Room 3",2.5,0,32],
	"Metroid Room 4": ["f_KilledMetroidRoom4", "Clear Metroid Room 4",0,1,32],
	"Glass Tunnel": ["f_MaridiaTubeBroken", "Break Maridia Tube",-0.5,2,16],
	"Shaktool Room": ["f_ShaktoolDoneDigging", "Clear Shaktool Room",0,0,32],
	"Acid Statue Room": ["f_UsedAcidChozoStatue", "Use Acid Statue",0,0.5,32],
	"Bowling Alley": ["f_UsedBowlingStatue", "Use Bowling Statue",4,1,32],
	"Pit Room": ["f_ClearedPitRoom", "Clear Pit Room",1,0,32],
	"Baby Kraid Room": ["f_ClearedBabyKraidRoom", "Clear Baby Kraid Room",5,0,32],
	"Plasma Room": ["f_ClearedPlasmaRoom", "Clear Plasma Room",0.5,1,32],
	"Metal Pirates Room": ["f_ClearedMetalPiratesRoom", "Clear Metal Pirates Room",1,0,32],
	"Parlor And Alcatraz": ["f_ZebesAwake", "Awaken Zebes",2, 0.5,24],
	"Climb": ["f_ZebesAwake", "Awaken Zebes",1,4,24],
	"Construction Zone": ["f_ZebesAwake", "Awaken Zebes",0,1.5,24],
	"The Final Missile": ["f_ZebesAwake", "Awaken Zebes",0,0,24],
	"Morph Ball Room": ["f_ZebesAwake", "Awaken Zebes",5,2,24],
	"Blue Brinstar Energy Tank Room": ["f_ZebesAwake", "Awaken Zebes",0,2.5,24],
};
const startOffsets = {
"Blue Brinstar Elevator Room":       [12, 10],
"Bomb Torizo Room":       [8, 13],
"Climb Top":       [24, 8],
"Climb Top Right":       [40, 8],
"Climb Bottom Right":       [39,120],
"Climb Bottom Left":       [12,138],
"Crateria Power Bomb Room":  [3.5, 10],
"Crateria Super Room Top Left":       [4, 10],
"Crateria Super Room Top Middle":       [42.5, 10],
"Crateria Super Room Bottom Left":       [35,        122],
"Crateria Super Room Bottom Right":[56, 122],
"Final Missile Bombway Left":[3.5, 10],
"Final Missile Bombway Right":[28.5, 10],
"Flyway":[40, 13],
"Landing Site Gauntlet Entrance":[29.5, 41],
"Landing Site Top Right":[134, 24],
"Parlor Top Left":[10.5, 9],
"Alcatraz":[57, 26],
"Parlor Bottom":[24, 71],
"Pit Room":[5.5, 10],
"Pre-Map Flyway":[40, 13],
"Gauntlet Energy Tank Room Left":[3.5, 10],
"Gauntlet Entrance Left":[5.5, 9],
"Gauntlet Entrance Right":[74.5, 9],
"Green Brinstar Elevator Room":[3.5, 10],
"Green Pirates Shaft Top":[12.5, 10],
"Green Pirates Shaft Middle":[8, 74],
"Green Pirates Shaft Bottom":[8, 106],
"Lower Mushrooms":[24, 13],
"Statues Hallway":[24, 12],
"Bowling Alley Path":[27, 10],
"Crab Maze Left":[39, 23],
"Crab Maze Right":[55, 26],
"Crateria Kihunter Room":[22, 26],
"East Ocean Top Right":[107, 75],
"East Ocean Center":[84, 78],
"East Ocean Left":[7.5, 75],
"Forgotten Highway Elbow":[5, 13],
"Forgotten Highway Elevator":[8, 7],
"Forgotten Highway Kago Room":[6.5, 40],
"Homing Geemer Room":[8, 10],
"Red Brinstar Elevator Room":[8, 7],
"West Ocean Top":[4.5, 23],
"West Ocean Bottom":[7.5, 75],
"Blue Brinstar Boulder Room":[27.5, 13],
"Blue Brinstar Energy Tank Room Bottom":[24, 45],
"Blue Brinstar Energy Tank Room Top":[43.5, 10],
"Construction Zone Bottom":[3.5, 26],
"Construction Zone Top":[8, 8],
"Morph Ball Room Left":[24, 44],
"Early Supers Room Left":[5, 28],
"Early Supers Room Right":[40, 28],
"Etecoon Energy Tank Room Bottom Left":[4.5, 26],
"Green Brinstar Fireflea Room":[5, 26],
"Green Brinstar Main Shaft Top":[8, 106],
"Green Brinstar Main Shaft Bottom":[24, 125],
"Green Hill Zone Left":[24, 28],
"Noob Bridge":[40, 12],
"Big Pink Top Left":[19.5,10],
"Big Pink Middle Right":[75,90],
"Big Pink Bottom Right":[56,106],
"Big Pink Bottom Left":[4.5,154],
"Dachora Room Top Left":[56,12],
"Dachora Room Top Right":[72,12],
"Dachora Room Bottom":[72,108],
"Pink Brinstar Hopper Room Right":[25.75,26],
"Pink Brinstar Power Bomb Room Bottom Right":[28.5,26],
"Waterway Energy Tank Room":[21.5,8],
"Alpha Power Bomb Room":[44.5,10],
"Bat Room":[4,11],
"Below Spazer Top Right":[22,11],
"Below Spazer Top Left":[5,7],
"Caterpillar Room Right":[42.5,58],
"Caterpillar Room Left":[6,90],
"Hellway":[42,10],
"Red Brinstar Fireflea Room Left":[4.5,10],
"Red Brinstar Fireflea Room Right":[77,28],
"Red Tower Top":[8,10],
"Red Tower Bottom":[8,154],
"Red Tower Center":[3,106],
"X-Ray Scope Room Right":[26,10],
"Kraid Eye Door Room":[12.5,10],
"Warehouse Entrance Left":[12,10],
"Warehouse Entrance Right":[44.5,11],
"Warehouse Kihunter Room Right":[60.5,10],
"Warehouse Kihunter Room Bottom":[26,26],
"Warehouse Zeela Room Right":[24,26],
"Acid Snakes Tunnel Farm":[8,10],
"Bat Cave Farm":[10,10],
"Bubble Mountain Center":[4.5,42],
"Bubble Mountain Bottom Left":[4,58],
"Cathedral Entrance":[11,22],
"Cathedral Left":[6.5,26],
"Cathedral Right":[41.5,16],
"Double Chamber Left":[24,29.5],
"Double Chamber Right":[59.5,10],
"Frog Speedway Left":[24,10],
"Frog Speedway Right":[88,10],
"Green Bubbles Missile Room Left":[3.5,10],
"Green Bubbles Missile Room Right":[29,10],
"Kronic Boost Room Left":[6,25],
"Kronic Boost Room Right":[26,25],
"Lava Dive Room Left":[21,12],
"Lava Dive Room Right":[54,9],
"Lower Norfair Elevator":[8,10],
"Magdollite Tunnel Left":[3.5,10],
"Magdollite Tunnel Right":[44.5,10],
"Purple Farming Room":[4,10],
"Purple Shaft":[3.5,42],
"Red Pirate Shaft":[11.5,10],
"Rising Tide Left":[18.5,11],
"Rising Tide Right":[76.5,10],
"Single Chamber Left":[12.5,26],
"Single Chamber Right":[83,7],
"Upper Norfair Farming Room":[9.5,26],
"Volcano Room Left":[12,42],
"Volcano Room Right":[40,37],
"Business Center":[10,90],
"Crocomire Escape Right":[46,10],
"Crocomire Escape Left":[4,10],
"Crocomire Speedway Left":[24,13],
"Crocomire Speedway Bottom Right":[200,40],
"Crumble Shaft Bottom":[5.5,60],
"Hi Jump Energy Tank Room Left":[6,25],
"Ice Beam Acid Room Left":[11.5,10],
"Ice Beam Gate Room Center Left":[56,42],
"Ice Beam Gate Room Right":[88,42],
"Ice Beam Gate Room Bottom":[56,56],
"Ice Beam Snake Room Top":[8,10],
"Ice Beam Snake Room Bottom":[3.5,38],
"Ice Beam Snake Room Right":[26.5,28],
"Ice Beam Tutorial Room Left":[3.5,10],
"Ice Beam Tutorial Room Right":[28.5,10],
"Crocomire's Room":[24,11],
"Grapple Tutorial Room 1":[8,10],
"Grapple Tutorial Room 2 Bottom":[6,24],
"Grapple Tutorial Room 2 Top":[12,11],
"Grapple Tutorial Room 3 Right":[44.5,10],
"Grapple Tutorial Room 3 Left":[21.5,10],
"Post Crocomire Farming Room":[3,27],
"Post Crocomire Jump Room Left":[6.5,26],
"Post Crocomire Jump Room Right":[124.5,39],
"Post Crocomire Missile Room":[3.5,10],
"Post Crocomire Shaft Top":[6.5,10],
"Post Crocomire Shaft Right":[12.5,58],
"Acid Statue Room Top":[25.5,12],
"Acid Statue Room Bottom":[14.5,43],
"Fast Ripper Room Right":[56,10],
"Golden Torizo's Room Top Left":[3.5,10],
"Screw Attack Room Top":[8,10],
"Amphitheatre Bottom Left":[6,69],
"Amphitheatre Top Right":[25.5,24],
"Fast Pillars Setup Room":[8,43],
"Lower Norfair Escape Power Bomb Room":[8,10],
"Lower Norfair Farming Room Right":[44.5,10],
"Lower Norfair Farming Room Left":[9,11],
"Lower Norfair Fireflea Room":[8,10.5],
"Lower Norfair Spring Ball Maze Room Center":[39,9],
"Lower Norfair Spring Ball Maze Room Right":[72,13],
"Main Hall Left":[13.5,41],
"Main Hall Elevator":[72,42],
"Mickey Mouse Room":[56,21],
"Pillar Room Right":[52.5,9],
"Pillar Room Left":[4,10],
"Red Kihunter Shaft Top":[8.5,10],
"Red Kihunter Shaft Bottom Left":[7.5,72],
"Red Kihunter Shaft Bottom Right":[40,77],
"Ridley Tank Room":[4.5,12],
"The Worst Room In The Game Top":[3.5,10],
"The Worst Room In The Game Right":[12,26],
"Three Musketeers' Room":[24,10],
"Wasteland Right":[88,7],
"Wasteland Bottom":[20.5,42],
"Boyon Gate Hall Left":[19,10],
"Boyon Gate Hall Right":[26.5,10],
"Crab Hole Top":[10.5,13],
"Crab Hole Bottom":[11,29],
"Crab Tunnel Left":[8.5,13],
"Crab Tunnel Right":[53,13],
"Fish Tank Top Right":[56,8],
"Fish Tank Left":[10.5,23.5],
"Glass Tunnel Bottom":[8,39.5],
"Glass Tunnel Top":[8,9],
"Main Street Top":[24,10],
"Main Street Middle":[7,38],
"Main Street Bottom":[20.5,124],
"Mama Turtle Room":[41,61],
"Mt. Everest Top Left":[8,13],
"Mt. Everest Top Right":[90,11],
"Mt. Everest Bottom Left":[66,60],
"Mt. Everest Bottom Right":[72,61],
"Red Fish Room Top Left":[13,8],
"Red Fish Room Top Right":[36,9],
"West Glass Tube Tunnel":[8,10],
"Aqueduct Top Left":[8.5,8],
"Aqueduct Center Left":[4.5,26],
"Aqueduct Bottom":[40,42],
"Below Botwoon Energy Tank":[61.5,12],
"Botwoon Energy Tank Room Left":[8,11],
"Botwoon Energy Tank Room Right":[104,10],
"Botwoon Hallway Left":[8,13],
"Botwoon Hallway Right":[60,10],
"Botwoon's Room":[25.5,11],
"Colosseum Left":[44.5,8],
"Colosseum Right":[64.5,8],
"Crab Shaft Top":[8,7],
"Crab Shaft Center":[8,42],
"Crab Shaft Bottom":[8,60],
"East Cactus Alley Room Left":[5,10],
"East Cactus Alley Room Right":[77,26],
"East Sand Hole":[25,11],
"Halfie Climb Room Right":[40,39],
"The Precious Room":[8,23],
"Maridia Elevator Room Center":[9,76],
"Northwest Maridia Bug Room Left":[5.5,10],
"Northwest Maridia Bug Room Center":[9,76],
"Kassiuz Room":[5.5,59],
"Plasma Spark Room Top":[39,9],
"Plasma Spark Room Bottom":[52,71],
"Pseudo Plasma Spark Room Top":[56.5,26],
"Thread The Needle Room":[53,9],
"Watering Hole":[4,12],
"East Pants Room":[8,10],
"East Sand Hall Left":[4,10],
"East Sand Hall Right":[44.5,10],
"Oasis":[8,26],
"Shaktool Room Left":[5,12],
"Shaktool Room Right":[59,12],
"West Sand Hall Left":[11,12],
"West Sand Hall Right":[60.5,10],
"Attic":[3,10],
"Basement Left":[40,7],
"Basement Right":[73,13],
"Bowling Alley Top":[59,10],
"Bowling Alley Center":[73.25,27],
"Bowling Alley Bottom":[21,44],
"Electric Death Room":[8,7],
"Wrecked Ship East Super Room":[37,13],
"Wrecked Ship Energy Tank Room":[43,10],
"Wrecked Ship Entrance":[24,10],
"Wrecked Ship Main Shaft Top":[72,29],
"Wrecked Ship Main Shaft Right":[92.5,106],
"Wrecked Ship Main Shaft Bottom":[66,118],
"Big Boy Room":[54,13],
"Dust Torizo Room":[25,12],
"Metroid Room 1 Right":[87,12],
"Rinka Shaft":[11,12],
"Seaweed Room":[3.5,9],
"Tourian Escape Room 1":[25,10],
"Tourian Escape Room 2":[8,8],
"Tourian Escape Room 3":[22,9],
"Tourian Escape Room 4":[44.5,45],
"Tourian Eye Door Room":[26,12],
"Tourian First Room":[8.5,58],
"Amphitheatre Bottom Left":[6,69],
"Crateria Map Room":[3.5,10],
"Crateria Save Room":[12.5,10],
"The Final Missile":[11.5,10],
"Gauntlet Energy Tank Room Right":[92,10],
"Terminator Room":[89,11],
"The Moat Left":[13,25],
"The Moat Right":[28,10],
"Billy Mays Room":[11.5,13],
"First Missile Room":[10.5,10],
"Morph Ball Room Right":[104,45],
"Brinstar Map Room":[12.5,10],
"Brinstar Reserve Tank Room":[0,8],
"Etecoon Energy Tank Room Top":[20,10],
"Etecoon Save Room":[12.5,10],
"Etecoon Super Room":[10,11],
"Green Brinstar Missile Refill":[12.5,10],
"Big Pink Save Room":[12.5,10],
"Dachora Energy Refill":[12.5,10],
"Hopper Energy Tank Room":[6,13],
"Sloaters Refill":[12.5,10],
"Kraid Recharge Station":[12,12],
"Kraid Save Room":[5.5,12],
"Varia Suit Room":[11,12],
"Warehouse Entrance Pit":[26,21],
"Frog Savestation":[5.5,12],
"Lower Norfair Elevator Save Room":[12.5,10],
"Nutella Refill":[10,12],
"Wave Beam Room":[3.5,10],
"Crocomire Save Room":[3,10],
"Hi Jump Boots Room":[11.5,10],
"Hi Jump Energy Tank Room Right":[20.5,10],
"Ice Beam Room":[5.5,10],
"Norfair Map Room":[12.5,10],
"Grapple Beam Room":[10.5,42],
"Post Crocomire Power Bomb Room":[12,10],
"Post Crocomire Save Room":[5.5,12],
"Screw Attack Room Middle":[8,34],
"Screw Attack Room Bottom":[4.5,43],
"Red Kihunter Shaft Save Room":[5.5,12],
"Glass Tunnel Save Room":[5.5,12],
"Aqueduct Save Room":[12.5,10],
"Draygon Save Room":[5.5,12],
"Maridia Health Refill Room":[6,12],
"Maridia Missile Refill Room":[6,12],
"West Sand Hole":[17,12],
"Forgotten Highway Save Room":[5.5,12],
"Gravity Suit Room":[11.5,10],
"Wrecked Ship East Missile Room":[7,10],
"Wrecked Ship Map Room":[12.5,10],
"Wrecked Ship Save Room":[5.5,12],
"Wrecked Ship West Super Room":[8,12],
"Lower Tourian Save Room":[12.5,10],
"Tourian Recharge Room":[11,12],
"Tourian Map Room":[3.5,10],
"Speed Booster Room":[0,5.5],
};