name: Check Rust

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  RUST_TOOLCHAIN: "1.94.1"

defaults:
  run:
    working-directory: ./rust

jobs:
  formatting:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          components: rustfmt
      - run: cargo fmt --check
  clippy:
    name: Clippy Lints
    env:
      RUSTFLAGS: "-Dwarnings"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          components: clippy
      - run: cargo clippy --all-targets
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
      - run: cargo test
